#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : nfv-vim
Version  : 80a73c0af6752f535356cb4f937c0f11d765a798
Release  : 7
URL      : https://github.com/openstack/stx-nfv/archive/80a73c0af6752f535356cb4f937c0f11d765a798.tar.gz
Source0  : https://github.com/openstack/stx-nfv/archive/80a73c0af6752f535356cb4f937c0f11d765a798.tar.gz
Summary  : Nova Computer API Proxy
Group    : Development/Tools
License  : Apache-2.0
Requires: nfv-vim-bin
Requires: nfv-vim-python
Requires: librt.so.1()(64bit)
Requires: nfv-vim-legacypython
Requires: six
BuildRequires : buildreq-distutils
BuildRequires : buildreq-distutils3
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : six
BuildRequires : tox
BuildRequires : virtualenv
Patch1: 0001-change-sysconfig-dir.patch

%description
Nova Computer API Proxy

%package bin
Summary: bin components for the nfv-vim package.
Group: Binaries

%description bin
bin components for the nfv-vim package.


%package legacypython
Summary: legacypython components for the nfv-vim package.
Group: Default
Requires: python-core

%description legacypython
legacypython components for the nfv-vim package.


%package python
Summary: python components for the nfv-vim package.
Group: Default

%description python
python components for the nfv-vim package.


%prep
%setup -q -n stx-nfv-80a73c0af6752f535356cb4f937c0f11d765a798
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1538105075
pushd nfv/nfv-vim
python2 setup.py build -b py2
popd

%install
## install_prepend content
%global subdir 'nfv/nfv-vim'
sed -i -e 's/${sysconfdir}/\/usr\/local\/etc/g' %{subdir}/scripts/vim
sed -i -e 's/${sysconfdir}/\/usr\/local\/etc/g' %{subdir}/scripts/vim-api
sed -i -e 's/${sysconfdir}/\/usr\/local\/etc/g' %{subdir}/scripts/vim-webserver
sed -i -e 's/${sysconfdir}/\/usr\/local\/etc/g' %{subdir}/nfv_vim/config.ini
## install_prepend end
rm -rf %{buildroot}
pushd nfv/nfv-vim
python2 -tt setup.py build -b py2 install --root=%{buildroot}
popd
## install_append content
%global _sysconfdir '/usr/local/etc'
install -d -m 755 %{buildroot}/usr/lib/ocf/resource.d/nfv
install -p -D -m 755 %{subdir}/scripts/vim %{buildroot}/usr/lib/ocf/resource.d/nfv/vim
install -p -D -m 755 %{subdir}/scripts/vim-api %{buildroot}/usr/lib/ocf/resource.d/nfv/vim-api
install -p -D -m 755 %{subdir}/scripts/vim-webserver %{buildroot}/usr/lib/ocf/resource.d/nfv/vim-webserver
install -d -m 755 %{buildroot}/usr/local/etc/nfv/
install -d -m 755 %{buildroot}/usr/local/etc/nfv/vim/
install -p -D -m 600 %{subdir}/nfv_vim/config.ini %{buildroot}/%{_sysconfdir}/nfv/vim/config.ini
install -p -D -m 600 %{subdir}/nfv_vim/debug.ini %{buildroot}/%{_sysconfdir}/nfv/vim/debug.ini
%clean
## install_append end

%files
%defattr(-,root,root,-)
/usr/lib/ocf/resource.d/nfv/vim
/usr/lib/ocf/resource.d/nfv/vim-api
/usr/lib/ocf/resource.d/nfv/vim-webserver
/usr/local/etc/nfv/vim/config.ini
/usr/local/etc/nfv/vim/debug.ini

%files bin
%defattr(-,root,root,-)
/usr/bin/nfv-vim
/usr/bin/nfv-vim-api
/usr/bin/nfv-vim-manage
/usr/bin/nfv-vim-webserver

%files legacypython
%defattr(-,root,root,-)
/usr/lib/python2*/*

%files python
%defattr(-,root,root,-)
